### ISSUE TITLE
Any alignment tools recommended?

### ISSUE THREAD

**Issue by Zoeyoungxy** [asylvz/SVarp#1]
Hi,
So excited to see this pangenome-based SV caller! Would you please give me some detailed information to use svarp?
1. An alignment file in .gaf format is needed, I wonder which aligner is suitable for svarp, GraphAligner or minigraph? Is there any tools and parameters recommended to align the sequence to a GFA graph ?
2. Does the input parameter `--fasta (-f) ` mean the query sequence? The .gaf file is already provided, why do we need the fasta file as well? Is it to provide insertion sequence information?

Thanks

-Zoey

**Comment by asylvz** [comment]
Hi Zoey,

1. You can use both but we mostly tested with minigraph due to runtime related reasons. This is a sample command for alignment: "minigraph -cx lr XXX.gfa XXX.fasta.gz --vc -t 32 > OUT.gaf"
2. Fasta is needed for the local assembly that we use

Best,
Arda
