### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LuyaoRen** [asylvz/SVarp#2]
Hi,

I am trying to use SVarp to detect SV from pangenome graph using this comman line `svarp -a sample.gaf -g ref_graph.gfa -f sample.fq.gz -i sample`.

 `ref_graph.gfa` was generated by minigraph `minigraph -cxggs -t24 T2T-CHM13v2.fasta sample.hap1.fasta sample.hap2.fasta > ref_graph.gfa`, alignment was generated by minigraph `minigraph -t 24 -cx lr ref_graph.gfa sample.fq.gz > sample_aligned.gaf`. 

The error message was:
```

Using wtdbg2 for assembly...
No phase information provided (--phase). SVs will not be phased...

...hallo, merhaba, ola, salaam, hello!!! SVarp is running...

Parameters:
	Minimum read support: 5
	Minimum distance threshold: 100

	Minimum map ratio: 0.9
	Precise clipping (Graphaligner): 0.97
	Alignment score (Graphaligner): 5000


Input files:
	sample_aligned.gaf
	ref_graph.gfa
	sample.fq.gz

Log folder:
	/svarp_log/

Reading the GFA file
Reading the GAF file
Segmentation fault (core dumped)
```

Can you help me and identify which step I might have gotten wrong?
Thank you!

**Comment by asylvz** [comment]
Can you send me some lines from your GAF and GFA? e.g., **cat sample_aligned.gaf |head -n 5000 >dnm.gaf**

**Comment by LuyaoRen** [comment]
Hi,
I think I understand the problem now. Based on another issue, it seems that I forgot to include the `--vc` flag when aligning the sequences to the graph. I've successfully run SVarp and obtained svtigs fasta files. 
How can I get SV breakpoints next?

Thank you!

**Comment by asylvz** [comment]
We do not output SV breakpoints but you can use an assembly based SV discovery tool such as SVIM-asm or PAV for this (by giving the svtigs as input).
